### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by secretshardul** [ishalyminov/instapy-docker-heroku#1]
Getting this error on both Heroku and on MacOS Catalina. My `.env` file contains this line. Please help.
```
GECKODRIVER_PATH=/usr/local/bin/geckodriver
```

This was the logtrace
```
2020-08-29T15:59:58.738443+00:00 heroku[instapy.1]: State changed from starting to up
2020-08-29T16:00:00.624369+00:00 heroku[instapy.1]: Process exited with status 1
2020-08-29T16:00:00.663483+00:00 heroku[instapy.1]: State changed from up to crashed
2020-08-29T16:00:00.519842+00:00 app[instapy.1]: InstaPy Version: 0.6.10
2020-08-29T16:00:00.519866+00:00 app[instapy.1]:  ._.  ._.  ._.  ._.  ._.  ._. 
2020-08-29T16:00:00.519866+00:00 app[instapy.1]: Workspace in use: "./InstaPy"
2020-08-29T16:00:00.523037+00:00 app[instapy.1]: Traceback (most recent call last):
2020-08-29T16:00:00.523038+00:00 app[instapy.1]:   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
2020-08-29T16:00:00.523038+00:00 app[instapy.1]:     stdin=PIPE)
2020-08-29T16:00:00.523038+00:00 app[instapy.1]:   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
2020-08-29T16:00:00.523039+00:00 app[instapy.1]:     restore_signals, start_new_session)
2020-08-29T16:00:00.523039+00:00 app[instapy.1]:   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
2020-08-29T16:00:00.523039+00:00 app[instapy.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2020-08-29T16:00:00.523040+00:00 app[instapy.1]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/geckodriver': '/usr/local/bin/geckodriver'
```

**Comment by ishalyminov** [comment]
hi,

Maybe try removing GECKODRIVER_PATH from your docker env - so that InstaPy tries to download its own?

**Comment by danielrosero** [comment]
> hi,
> 
> Maybe try removing GECKODRIVER_PATH from your docker env - so that InstaPy tries to download its own?

Hi I tried this, using the `env_sample` file (that doesn't defines GECKODRIVER_PATH) and is not working.

Any ideas? 

Thanks @ishalyminov

**Comment by ishalyminov** [comment]
ok, maybe something changed in the recent InstaPy distribution - let me look into it
